title: What I would tell the Junior Me!
author: theArchitect
subtitle: Stuff which made me a bit more wiser as I got older.

url: "https://wiwttjm.github.io/"
baseurl: ""

footer_only_homepage: true
footer_url: "https://wiwttjm.github.io/"
footer_text: "Some Shifa Alumni"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Contact"
   link: "contact"
 - name: "Resources"
   link: "resource"
 - name: "Tags"
   link: "tag"
